
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpt-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gpt-runner
  template:
    metadata:
      labels:
        app: gpt-runner
    spec:
      containers:
      - name: gpt-runner
        image: asia-south1-docker.pkg.dev/autotrade-453303/gpt-repo/gpt-runner:latest
        command: ["python"]
        args: ["runner/gpt_runner.py"]
        env:
        - name: PAPER_MODE
          value: "true"
