# Updated YAML files for all bots + main runner + GPT runner
# Each has resource limits, proper env vars, and market-hour control logic via CMDs or future cron

---
# main.yaml (Orchestrator - main_runner.py)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main-runner
  template:
    metadata:
      labels:
        app: main-runner
    spec:
      containers:
      - name: main-runner
        image: asia-south1-docker.pkg.dev/autotrade-453303/gpt-repo/gpt-runner:latest
        command: ["python","runner/main_runner.py"]
        env:
        - name: PAPER_MODE
          value: "true"
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"