---
# Main Runner Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpt-runner-main
  namespace: gpt  
  labels:
    app: gpt-runner
    component: main
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gpt-runner
      component: main
  template:
    metadata:
      labels:
        app: gpt-runner
        component: main
    spec:
      serviceAccountName: gpt-runner-sa
      containers:
      - name: main-runner
        image: asia-south1-docker.pkg.dev/autotrade-453303/gpt-repo/gpt-runner:latest
        command: ["python", "main_runner.py"]
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "200m"
            memory: "512Mi"
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: openai-secret
              key: openai_key
        - name: PYTHONPATH
          value: "/app"
        volumeMounts:
        - name: logs
          mountPath: /app/logs
      volumes:
      - name: logs
        emptyDir: {}
