# options-trader.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: options-trader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: options-trader
  template:
    metadata:
      labels:
        app: options-trader
    spec:
      containers:
      - name: options-trader
        image: asia-south1-docker.pkg.dev/autotrade-453303/gpt-repo/gpt-runner:latest
        command: ["python","options_trading/options_runner.py"]
        env:
        - name: PAPER_MODE
          value: "true"
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"