import os

API_KEY = os.getenv("ZERODHA_API_KEY")
API_SECRET = os.getenv("ZERODHA_API_SECRET")
ACCESS_TOKEN = os.getenv("ZERODHA_ACCESS_TOKEN")  # Still needs to be updated daily
RISK_PER_TRADE = 200
INITIAL_CAPITAL = 9000
DAILY_LOSS_LIMIT = 600
STOCKS = ["RELIANCE", "TCS", "HDFCBANK", "INFY", "ICICIBANK"]
MIS_MARGIN = {
    "RELIANCE": 5,
    "TCS": 10,
    "HDFCBANK": 10,
    "INFY": 10,
    "ICICIBANK": 10
}
